# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://AceXking.github.io
date_format: "ordinal"
title: AceXking
subtitle: "故不积跬步，无以至千里;不积小流，无以成江海"
description: "wx的个人博客"
keywords: AceXking, W X, AceXking, wx
timezone: China/xian
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: W X
organization: 
organization_url: 
github_username: AceXking
location: xian, China
email: 443744345@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: AceXking/AceXking.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wxblog
    repo: blog-comments
    oauth:
        client_id: 45167035937aa9d09647
        client_secret: 18cf37b30d969e658a5f35aa9c7d0a382efb8a72
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: wxblog
    repo: blog-comments
    clientID: 45167035937aa9d09647
    clientSecret: 18cf37b30d969e658a5f35aa9c7d0a382efb8a72
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
